server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eattingwhat2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

  mvc:
    static-path-pattern: /static/**

  application:
    name: eattingwhat2



mybatis:
  mapper-locations: classpath:mapper/*.xml #指定xml配置文件的位置

file:
  uploadFolder: /usr/local/upload
  staticAccessPath: /static/upload/**
